experiment: 'SG_exp01_baseline'
accelerator: 'gpu'  # (cpu, gpu)
devices: '1'

optimizer:
  _target_: torch.optim.Adam
  lr: 0.1

max_epochs: 100

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 50
  gamma: 0.1

loss:
  negative_samples: 1



