experiment: 'SG_exp01_baseline'
accelerator: 'gpu'  # (cpu, gpu)
devices: '1'

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3

max_epochs: 50

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.1

loss:
  negative_samples: 3



