defaults:
  - w2v_config

model:
  _target_: shallow_encoders.word2vec.model.SkipGram
  embedding_size: 2
  max_norm: 1.0
  # vocab_size - unknown until dataset is loaded

datamodule:
  dataset_name: 'abcde'
  mode: 'sg'
  context_radius: 1
  max_length: 256
  is_graph: false

  batch_size: 4
  num_workers: 8

train:
  experiment: 'SG_exp01_baseline'
  accelerator: 'gpu'  # (cpu, gpu)
  devices: '1'

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.1

  max_epochs: 20

  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.1

  loss:
    negative_samples: 1

analysis:
  checkpoint: 'last.ckpt'

  closest_pairs:
    enable: true
    pairs_per_word: 3

  visualize_embeddings:
    enable: true

  semantics_test:
    enable: false