defaults:
  - w2v_config

model:
  _target_: shallow_encoders.word2vec.model.SkipGram
  embedding_size: 48
  max_norm: null

datamodule:
  dataset_name: 'wiki-text-103'
  mode: 'sg'
  context_radius: 5
  max_length: 128
  min_word_frequency: 25
  lemmatize: true

  batch_size: 16
  num_workers: 8

train:
  experiment: 'SG_exp01_baseline'
  accelerator: 'gpu'  # (cpu, gpu)
  devices: '1'

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-3

  max_epochs: 50

  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.1

  loss:
    negative_samples: 3

analysis:
  checkpoint: 'last.ckpt'

  closest_pairs: true
  closest_max_words: 500
  closest_pairs_per_word: 5

  visualize_embeddings: true
  visualize_embeddings_max_words: 250

  semantics_test: false
